language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
    # The default env behaviour: phpunit, no coverage, no style checks
  - PHPUNIT=true GROESTLCOIN_VERSION="2.16.3" NBOBTC_VERSION="2.0.2"

cache:
  directories:
    ${HOME}/groestlcoin

matrix:
  fast_finish: true

  exclude:
      # Disable phpunit test on 7.0, reenable with COVERAGE
    - php: 7.0
      env: PHPUNIT=true GROESTLCOIN_VERSION="2.16.3" NBOBTC_VERSION="2.0.2"

  include:
      # This reenables php7.0/phpunit test with COVERAGE
    - php: 7.0
      env: PHPUNIT=true GROESTLCOIN_VERSION="2.16.3" COVERAGE=true CODESTYLE=true EXAMPLES=true

      # 2.1.x
    - php: 7.2
      env: PHPUNIT=true GROESTLCOIN_VERSION="2.16.3" NBOBTC_VERSION="2.1.0"

sudo: false

install:
    - |
        if [ "$GROESTLCOIN_VERSION" != "" ] && [ ! -e "${HOME}/groestlcoin" ]; then
            mkdir ${HOME}/groestlcoin
        fi
    - |
        if [ "$GROESTLCOIN_VERSION" != "" ] && [ ! -e "${HOME}/groestlcoin/groestlcoin-$GROESTLCOIN_VERSION" ]; then
            cd ${HOME}/groestlcoin &&
            wget https://github.com/Groestlcoin/groestlcoin/releases/download/v2.16.3/groestlcoin-${GROESTLCOIN_VERSION}-x86_64-linux-gnu.tar.gz &&
            tar xvf groestlcoin-${GROESTLCOIN_VERSION}-x86_64-linux-gnu.tar.gz &&
            cd ${TRAVIS_BUILD_DIR}
        else
            echo "Had groestlcoind"
        fi

before_script:
    - travis_retry composer install --prefer-source
    - composer require nbobtc/bitcoind-php ${NBOBTC_VERSION}
    - if [ "${COVERAGE}" != "true" ] && [ "${TRAVIS_PHP_VERSION}" != "nightly" ]; then phpenv config-rm xdebug.ini && echo "xdebug disabled"; fi

script:
    - if [ "${PHPUNIT}" = "true" ]; then GROESTLCOINDSERVER_DEBUG_START=true make phpunit-ci; fi
    - if [ "${CODESTYLE}" = "true" ]; then make phpcs && echo "PHPCS OK"; fi

after_success:
    - if [ "${COVERAGE}" = "true" ]; then make scrutinizer; fi
