<?php

declare(strict_types=1);

namespace BitWasp\Test\Groestlcoind\Config;

use BitWasp\Groestlcoind\Config\Config;
use BitWasp\Groestlcoind\Config\FilesystemLoader;
use BitWasp\Groestlcoind\Config\FilesystemWriter;
use BitWasp\Test\Groestlcoind\TestCase;
use Matomo\Ini\IniReader;

class FilesystemTest extends TestCase
{
    /**
     * @var FilesystemLoader
     */
    private $loader;

    /**
     * @var FilesystemWriter
     */
    private $writer;

    public function setUp()
    {
        $this->loader = new FilesystemLoader(new IniReader());
        $this->writer = new FilesystemWriter();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testReadAndWrite()
    {
        $filename = $this->registerTmpFile("test-fs-create-and-read.conf");
        $this->assertFileNotExists($filename);

        $config = new Config([
            'rpcuser' => 'username',
            'rpcpassword' => 'username',
            'rpcallowip' => '1',
        ]);

        $this->writer->create($filename, $config);
        $again = $this->loader->load($filename);

        $this->assertEquals($config->all(), $again->all());
    }

    public function testSaveAndRead()
    {
        $filename = $this->registerTmpFile("test-fs-save-and-read.conf");
        $this->assertFileNotExists($filename);

        $config = new Config([
            'rpcuser' => 'username',
            'rpcpassword' => 'username',
            'rpcallowip' => '1',
        ]);

        $this->writer->create($filename, $config);
        $again = $this->loader->load($filename);

        $this->assertEquals($config->all(), $again->all());
    }
}
